-- Execute this script in your Supabase SQL Editor to create the audit_logs table

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    admin_name TEXT NOT NULL,
    action_type TEXT NOT NULL,
    description TEXT NOT NULL,
    branch TEXT DEFAULT 'noroeste' NOT NULL
);

-- Enable RLS and performance indices
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Allow public read access to audit logs (can be restricted if necessary, but matches system behavior)
CREATE POLICY "Permitir lectura publica de auditorias" ON public.audit_logs
    FOR SELECT USING (true);

-- Allow authenticated users or service role to insert logs
CREATE POLICY "Permitir insercion a usuarios autenticados" ON public.audit_logs
    FOR INSERT WITH CHECK (true);

-- Create indices for efficient filtering and ordering
CREATE INDEX IF NOT EXISTS idx_audit_logs_branch ON public.audit_logs(branch);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs(created_at DESC);
